# Generated by Django 5.2.1 on 2025-06-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collage',
            fields=[
                ('collage_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
