# Generated by Django 5.2.1 on 2025-06-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phone_no', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('collage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apapp.collage')),
            ],
        ),
    ]
