# Generated by Django 5.2.1 on 2025-06-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apapp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='total_student',
            field=models.IntegerField(default=0),
        ),
    ]
