# Generated by Django 5.2.1 on 2025-06-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apapp', '0003_collage_total_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='total_student',
        ),
    ]
