# Generated by Django 5.2.1 on 2025-06-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apapp', '0004_remove_collage_total_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='collage_name',
            new_name='collage_id',
        ),
    ]
