# Generated by Django 5.2.1 on 2025-07-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apapp', '0005_rename_collage_name_student_collage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('location', models.CharField(default='', max_length=30)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('NON IT', 'NON IT'), ('MIXED', 'MIXED')], default='IT', max_length=30)),
                ('about', models.TextField()),
                ('Active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='collage_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='apapp.collage'),
        ),
    ]
