# Generated by Django 5.2.1 on 2025-07-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apapp', '0006_company_alter_student_collage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.TextField()),
                ('phone_no', models.IntegerField(default=0, max_length=22)),
                ('posotion', models.CharField(choices=[('manager', 'MANAGER'), ('ml engineer', 'ML ENGINEER'), ('salesman', 'SALESMAN')], default='salesman', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apapp.company')),
            ],
        ),
    ]
