# Generated by Django 5.2.1 on 2025-07-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apapp', '0007_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(default='0', max_length=22),
        ),
    ]
